// @generated by protobuf-ts 2.5.0
// @generated from protobuf file "funcs.proto" (syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Funcs } from "./funcs";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { DownloadImageRespond } from "./funcs";
import type { DownloadImageRequest } from "./funcs";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service Funcs
 */
export interface IFuncsClient {
    /**
     * @generated from protobuf rpc: downloadImageToSave(DownloadImageRequest) returns (DownloadImageRespond);
     */
    downloadImageToSave(input: DownloadImageRequest, options?: RpcOptions): UnaryCall<DownloadImageRequest, DownloadImageRespond>;
}
/**
 * @generated from protobuf service Funcs
 */
export class FuncsClient implements IFuncsClient, ServiceInfo {
    typeName = Funcs.typeName;
    methods = Funcs.methods;
    options = Funcs.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: downloadImageToSave(DownloadImageRequest) returns (DownloadImageRespond);
     */
    downloadImageToSave(input: DownloadImageRequest, options?: RpcOptions): UnaryCall<DownloadImageRequest, DownloadImageRespond> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<DownloadImageRequest, DownloadImageRespond>("unary", this._transport, method, opt, input);
    }
}
